TRAIN_PATH = '../../../data/Lyrics/Training'
TEST_PATH = '../../../data/Lyrics/Test'
VAL_PATH = '../../../data/Lyrics/Validation'
LYRICS_DIR = '../../../data/Genre2'
LOG_PATH = '../../../data/log.txt'
TRAIN_FREQS = '../../../data/objects/trainFreqs.pkl'
VAL_FREQS = '../../../data/objects/valFreqs.pkl'
TEST_FREQS = '../../../data/objects/testFreqs.pkl'