PATH_TRAIN = '../../data/Lyrics/Training'
PATH_VAL = '../../data/Lyrics/Validation'
PATH_TEST = '../../data/Lyrics/Test'
LYRICS_DIR = '../../data/Genre9'
LOG_PATH = '../../data/log.txt'
PICKLE_DIR = '../../data/objects'
SENTIMENT_DIR = '../../data/NRC-Sentiment-Emotion-Lexicons/Lexicons/' \
				'NRC-Emotion-Lexicon-v0.92/NRC-Emotion-Lexicon-Wordlevel-v0.92.txt'
ALL_FREQS_TRAIN = '../../data/objects/allFreqsTrain.json'
ALL_FREQS_VAL = '../../data/objects/allFreqsVal.json'
ALL_FREQS_TEST = '../../data/objects/allFreqsTest.json'
GENRE_SONGS_TRAIN = '../../data/objects/genreSongsTrain.json'
GENRE_SONGS_VAL = '../../data/objects/genreSongsVal.json'
GENRE_SONGS_TEST = '../../data/objects/genreSongsTest.json'
GENRE_FREQS_TRAIN = '../../data/objects/genreFreqsTrain.json'
GENRE_FREQS_VAL = '../../data/objects/genreFreqsVal.json'
GENRE_FREQS_TEST = '../../data/objects/genreFreqsTest.json'
NUM_SONGS_TRAIN = '../../data/objects/numSongsTrain.json'
NUM_SONGS_VAL = '../../data/objects/numSongsVal.json'
NUM_SONGS_TEST = '../../data/objects/numSongsTest.json'
RESULTS = '../../data/objects/results.json'
SENTIMENT = '../../data/objects/sentiment.json'

MATRIX_OUTPUT = '../../data/output/confusionMatrix.txt'
PREC_OUTPUT = '../../data/output/precision.txt'
REC_OUTPUT = '../../data/output/recall.txt'